Windows-AMD-Nvidia-GPU:
    tags: 
        - Windows-AMD-Nvidia-GPU
    stage: build
    script:
        - dir
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'

Windows-AMD-GPU:
    tags:
        - Windows-AMD-GPU
    stage: test
    script:
        - wget -v https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe -OutFile msys2.exe
        - ./msys2.exe -y -oC:\
        - Remove-Item msys2.exe
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'

Windows-Intel-GPU:
    tags:
        - Windows-Intel-GPU
    stage: test
    script:
        - wget -v https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe -OutFile msys2.exe
        - ./msys2.exe -y -oC:\
        - Remove-Item msys2.exe
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'