build-job:
    tags: 
        - Windows-AMD-Nvidia-GPU
    stage: build
    script:
        - dir
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'

test-job1:
    tags:
        - Windows-AMD-Nvidia-GPU
    stage: test
    script:
        - echo "This job tests something"

test-job2:
    tags:
        - Windows-AMD-Nvidia-GPU
    stage: test
    script:
        - echo "This job tests something, but takes more time than test-job1"
        - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
        - echo "which simulates a test that runs 20 seconds longer than test-job1"
        - sleep 20

deploy-prod:
    tags:
        - Windows-AMD-Nvidia-GPU
    stage: deploy
    script:
        - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    environment: production