Windows-AMD-Nvidia-GPU:
    tags: 
        - Windows-AMD-Nvidia-GPU
    stage: build
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S git mingw-w64-x86_64-gcc make mingw-w64-x86_64-shaderc mingw-w64-x86_64-libpng'
        - C:\msys64\usr\bin\bash -lc './ci-build.sh'

Linux-AMD-GPU:
    tags:
        - Linux-AMD-GPU
    stage: build
    script:
        echo "Hello World"

Windows-AMD-GPU:
    tags:
        - Windows-AMD-GPU
    stage: build
    script:
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S git mingw-w64-x86_64-gcc make mingw-w64-x86_64-shaderc mingw-w64-x86_64-libpng'
        - C:\msys64\usr\bin\bash -lc './ci-build.sh'

Windows-Intel-GPU:
    tags:
        - Windows-Intel-GPU
    stage: build
    script:
        - $env:CHERE_INVOKING = 'yes'
        - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
        - C:\msys64\usr\bin\bash -lc ' '
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
        - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S git mingw-w64-x86_64-gcc make mingw-w64-x86_64-shaderc mingw-w64-x86_64-libpng'
        - C:\msys64\usr\bin\bash -lc './ci-build.sh'