#pragma once


/* optimal vertex buffer layout */

#define SGE_POSITION_BINDING_OPTIMAL 0
#define SGE_POSITION_LOCATION_OPTIMAL 0

#define SGE_NORMAL_BINDING_OPTIMAL 1
#define SGE_NORMAL_LOCATION_OPTIMAL 1

#define SGE_TANGENT_BINDING_OPTIMAL 2
#define SGE_TANGENT_LOCATION_OPTIMAL 2

#define SGE_TEXCOORD_BINDING_OPTIMAL 3
#define SGE_TEXCOORD_LOCATION_OPTIMAL 3

#define SGE_COLOR_BINDING_OPTIMAL 4
#define SGE_COLOR_LOCATION_OPTIMAL 4

/* separate vertex buffer layout */

#define SGE_POSITION_BINDING_SEPARATE 0
#define SGE_POSITION_LOCATION_SEPARATE 0

#define SGE_NORMAL_BINDING_SEPARATE 1
#define SGE_NORMAL_LOCATION_SEPARATE 1

#define SGE_TANGENT_BINDING_SEPARATE 2
#define SGE_TANGENT_LOCATION_SEPARATE 2

#define SGE_TEXCOORD_BINDING_SEPARATE 3
#define SGE_TEXCOORD_LOCATION_SEPARATE 3

#define SGE_COLOR_BINDING_SEPARATE 4
#define SGE_COLOR_LOCATION_SEPARATE 4

/* interleaved vertex buffer layout */

#define SGE_POSITION_BINDING_INTERLEAVED 0
#define SGE_POSITION_LOCATION_INTERLEAVED 0

#define SGE_NORMAL_BINDING_INTERLEAVED 0
#define SGE_NORMAL_LOCATION_INTERLEAVED 1

#define SGE_TANGENT_BINDING_INTERLEAVED 0
#define SGE_TANGENT_LOCATION_INTERLEAVED 2

#define SGE_TEXCOORD_BINDING_INTERLEAVED 0
#define SGE_TEXCOORD_LOCATION_INTERLEAVED 3

#define SGE_COLOR_BINDING_INTERLEAVED 0
#define SGE_COLOR_LOCATION_INTERLEAVED 4


#define SGE_SHADER_PROPERTY_MATERIAL_PROPERTIES_SET 4
#define SGE_SHADER_PROPERTY_MATERIAL_PROPERTIES_BINDING 0
#define SGE_SHADER_PROPERTY_TEXTURE0_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE0_BINDING 1
#define SGE_SHADER_PROPERTY_TEXTURE1_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE1_BINDING 2
#define SGE_SHADER_PROPERTY_TEXTURE2_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE2_BINDING 3
#define SGE_SHADER_PROPERTY_TEXTURE3_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE3_BINDING 4
#define SGE_SHADER_PROPERTY_TEXTURE4_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE4_BINDING 5
#define SGE_SHADER_PROPERTY_TEXTURE5_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE5_BINDING 6
#define SGE_SHADER_PROPERTY_TEXTURE6_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE6_BINDING 7
#define SGE_SHADER_PROPERTY_TEXTURE7_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE7_BINDING 8
#define SGE_SHADER_PROPERTY_TEXTURE8_SET 4
#define SGE_SHADER_PROPERTY_TEXTURE8_BINDING 9
