#pragma once


/* optimal vertex buffer layout */

#define SGE_POSITION_BINDING_OPTIMAL 0
#define SGE_POSITION_LOCATION_OPTIMAL 0

#define SGE_NORMAL_BINDING_OPTIMAL 0
#define SGE_NORMAL_LOCATION_OPTIMAL 0

#define SGE_TANGENT_BINDING_OPTIMAL 0
#define SGE_TANGENT_LOCATION_OPTIMAL 0

#define SGE_TEXCOORD_BINDING_OPTIMAL 0
#define SGE_TEXCOORD_LOCATION_OPTIMAL 0

#define SGE_COLOR_BINDING_OPTIMAL 0
#define SGE_COLOR_LOCATION_OPTIMAL 0

/* separate vertex buffer layout */

#define SGE_POSITION_BINDING_SEPARATE 0
#define SGE_POSITION_LOCATION_SEPARATE 0

#define SGE_NORMAL_BINDING_SEPARATE 1
#define SGE_NORMAL_LOCATION_SEPARATE 1

#define SGE_TANGENT_BINDING_SEPARATE 2
#define SGE_TANGENT_LOCATION_SEPARATE 2

#define SGE_TEXCOORD_BINDING_SEPARATE 3
#define SGE_TEXCOORD_LOCATION_SEPARATE 3

#define SGE_COLOR_BINDING_SEPARATE 4
#define SGE_COLOR_LOCATION_SEPARATE 4

/* interleaved vertex buffer layout */

#define SGE_POSITION_BINDING_INTERLEAVED 0
#define SGE_POSITION_LOCATION_INTERLEAVED 0

#define SGE_NORMAL_BINDING_INTERLEAVED 0
#define SGE_NORMAL_LOCATION_INTERLEAVED 1

#define SGE_TANGENT_BINDING_INTERLEAVED 0
#define SGE_TANGENT_LOCATION_INTERLEAVED 2

#define SGE_TEXCOORD_BINDING_INTERLEAVED 0
#define SGE_TEXCOORD_LOCATION_INTERLEAVED 3

#define SGE_COLOR_BINDING_INTERLEAVED 0
#define SGE_COLOR_LOCATION_INTERLEAVED 4
