
#pragma once

typedef enum vulkan_render_target_type_t
{
	VULKAN_RENDER_TARGET_TYPE_UNDEFINED = 0,
	VULKAN_RENDER_TARGET_TYPE_COLOR_TEXTURE,
	VULKAN_RENDER_TARGET_TYPE_DEPTH_TEXTURE,
	VULKAN_RENDER_TARGET_TYPE_COLOR_CUBEMAP,
	VULKAN_RENDER_TARGET_TYPE_DEPTH_CUBEMAP
} vulkan_render_target_type_t;

