#if defined(HEADER_CONFIGURATION_SYSTEM_HEADER) && !defined(GLOBAL_HEADER)
#	undef HEADER_CONFIGURATION_SYSTEM_HEADER
#endif

#if defined(HEADER) && !defined(GLOBAL_HEADER)
#	undef HEADER
#endif

#if defined(HPML_HEADER) && !defined(GLOBAL_HEADER)
#	undef HPML_HEADER
#endif

#if defined(HEADER_CONFIGURATION_SYSTEM_IMPLEMENTATION) && !defined(GLOBAL_IMPLEMENATION)
#	undef HEADER_CONFIGURATION_SYSTEM_IMPLEMENTATION
#endif

#if defined(IMPLEMENTATION) && !defined(GLOBAL_IMPLEMENATION)
#	undef IMPLEMENTATION
#endif

#if defined(HPML_IMPLEMENTATION) && !defined(GLOBAL_IMPLEMENATION)
#	undef HPML_IMPLEMENTATION
#endif

#if defined(HEADER_CONFIGURATION_SYSTEM_DEBUG_MODE) && !defined(GLOBAL_DEBUG)
#	undef HEADER_CONFIGURATION_SYSTEM_DEBUG_MODE
#endif

#if defined(DEBUG_MODE) && !defined(GLOBAL_DEBUG)
#	undef DEBUG_MODE
#endif

#if defined(DEBUG) && !defined(GLOBAL_DEBUG)
#	undef DEBUG
#endif

#if defined(HEADER_CONFIGURATION_SYSTEM_RELEASE_MODE) && !defined(GLOBAL_RELEASE)
# 	undef HEADER_CONFIGURATION_SYSTEM_RELEASE_MODE
#endif

#if defined(RELEASE_MODE) && !defined(GLOBAL_RELEASE)
#	undef RELEASE_MODE
#endif

#if defined(RELEASE) && !defined(GLOBAL_RELEASE)
#	undef RELEASE
#endif