#ifdef HEADER_CONFIGURATION_SYSTEM_HEADER
#	undef HEADER_CONFIGURATION_SYSTEM_HEADER
#endif

#ifdef HEADER
#	undef HEADER
#endif

#ifdef HPML_HEADER
#	undef HPML_HEADER
#endif

#ifdef HEADER_CONFIGURATION_SYSTEM_IMPLEMENTATION
#	undef HEADER_CONFIGURATION_SYSTEM_IMPLEMENTATION
#endif

#ifdef IMPLEMENTATION
#	undef IMPLEMENTATION
#endif

#ifdef HPML_IMPLEMENTATION
#	undef HPML_IMPLEMENTATION
#endif

#ifdef HEADER_CONFIGURATION_SYSTEM_DEBUG_MODE
#	undef HEADER_CONFIGURATION_SYSTEM_DEBUG_MODE
#endif

#ifdef DEBUG_MODE
#	undef DEBUG_MODE
#endif

#ifdef DEBUG
#	undef DEBUG
#endif

#ifdef HEADER_CONFIGURATION_SYSTEM_RELEASE_MODE
# 	undef HEADER_CONFIGURATION_SYSTEM_RELEASE_MODE
#endif

#ifdef RELEASE_MODE
#	undef RELEASE_MODE
#endif

#ifdef RELEASE
#	undef RELEASE
#endif