[Name("My Theme 1")]
[Model("Theme Model 1")]
[Model("Theme Model 2")]
[Model("Theme Model 3")]
Theme
{
    LargeButton.IdleColor = green { };
    LargeButton.HoverColor = red { };
    LargeButton.PressColor = grey { };
    SmallButton.IdleColor = green { };
    SmallButton.HoverColor = red { 1.0f };
    SmallButton.PressColor = grey { 1.0f };
    Folder.Open = "../textures/Thalita-Torres-Office-Archive-folders.512.png";
    Folder.Open.VG = "svg_files/close-cross-symbol-in-a-circle-svgrepo-com.svg";
    Folder.Close = "icons/Folder-Close.png";
    [Float]
    AnotherButton.AlphaValue = 0.7f;
    [String]
    Label.Value = "Hello World From Theme 1";
    [Float]
    AnotherLabel.Color.r = 1.0f;
    [Float]
    AnotherLabel.Color.g = 0.0f;
    [Float]
    AnotherLabel.Color.b = 1.0f;
    [Float]
    AnotherLabel.Color.a = 1.0f;
}
