#ifndef __EXCEPTION_DECLARATIONS_H__
#define __EXCEPTION_DECLARATIONS_H__

declare_exception(METHOD_NOT_IMPLEMENTED);
declare_exception(ACCESS_TO_RESTRICTED_CODE);
declare_exception(DIVIDE_BY_ZERO);
declare_exception(INVERSION_OF_SINGULAR_MATRIX);

#endif/*__EXCEPTION_DECLARATIONS_H__*/