#ifndef __EXCEPTION_DEFINITIONS_H__
#define __EXCEPTION_DEFINITIONS_H__

define_exception(METHOD_NOT_IMPLEMENTED);
define_exception(ACCESS_TO_RESTRICTED_CODE);
define_exception(DIVIDE_BY_ZERO);
define_exception(INVERSION_OF_SINGULAR_MATRIX);

#endif/*__EXCEPTION_DEFINITIONS_H__*/