name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Compiler Test
      run: gcc --version
    - name: Build System Test
      run: mingw32-make --version
    - name: Version Control System Test
      run: git --version
    - name: Git setup
      run: |
          git config --global user.email "rp0412204@gmail.com" 
          git config --global user.name "ravi688"
    - name: Setup Git submodules
      run: mingw32-make -s setup
    - name: Update Git submodules
      run: mingw32-make -s update
    - name: build-debug
      run: mingw32-make -s build
    - name: cleaning
      run: mingw32-make -i -s clean
