name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Compiler Test
      run: gcc --version
    - name: Build System Test
      run: mingw32-make --version
    - name: Setup & Updating Git submodules
      run: mingw32-make -s setup
    - name: build-debug
      run: mingw32-make -s build
    - name: cleaning
      run: mingw32-make -i -s clean
