name: MSYS2
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msys2-mingw64:
    runs-on: self-hosted
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
