name: MSYS2
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-gcc make mingw-w64-x86_64-shaderc
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Required Package Installs
        run: |
          sudo apt-get update
          sudo apt-get install -y vulkan-tools
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt-get update
          sudo apt-get install -y vulkan-sdk
          sudo apt-get install -y build-essential
          sudo apt-get install -y libz-dev
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y libbrotli-dev
      - name: CI-Build
        run: |
          sudo chmod +x ./ci-build.sh
          echo "Building..."
          ./ci-build.sh
