name: MSYS2
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git gcc make mingw-w64-x86_64-shaderc
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
